{
  username = "enkai";
  userFullName = "Enkaiyuegure";
  userEmail = "enkaiyuegure@outlook.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$6$cFYVfLoLFZURhDXT$ydrUHmAi792bvc53jdVxuxippqbBJlVQqV/L/qZlfZNF5T0U9V0rP1o2nXlaKz0s4bsZNk.dkjeFtDf2XimOM1";
}
